### ISSUE TITLE
Update HTTPoison

### ISSUE THREAD

**Issue by ghost** [ravernkoh/gollum#1]
Gollum requires an old (0.x) version of HTTPoison. Since the latest version is somewhere around 1.5, this can cause dependency conflicts.

**Comment by ravern** [comment]
Hey, thanks for the report! I'll update this by Sunday.

**Comment by ravern** [comment]
Fixed and published as `v0.3.2`.

_My brain failed me and I skipped `v0.3.0` and `v0.3.1` for some reason 😅_
